In [1]:
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd
import os
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

2024-02-14 08:19:33.413061: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-14 08:19:33.413105: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-14 08:19:33.462483: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-14 08:19:33.563074: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-14 08:19:34.266486: W tensorflow/compiler/tf2

In [2]:
# load lorfs.csv
lorfs_short = pd.read_csv('Data/Test/lorfs_short.csv')
lorfs_medium = pd.read_csv('Data/Test/lorfs_medium.csv')
lorfs_long = pd.read_csv('Data/Test/lorfs_long.csv')

# sort by length
lorfs_short = lorfs_short.sort_values(by='length')
lorfs_medium = lorfs_medium.sort_values(by='length')
lorfs_long = lorfs_long.sort_values(by='length')

def filter_non_aa(df):
    non_amino_acids = ['\*','x','0','1',';','5','4','7','8','9','>','_','\.','2','\-','3','6']
    pattern = '|'.join(non_amino_acids)

    print("Original shape:", df.shape)
    orginal_shape = df.shape
    # Make sure the sequence column doesn't contain any of these characters
    df = df[~df['Sequence'].str.contains(pattern, regex=True, case=False, na=False)]
    # Print new shape
    print("New shape after filtering:", df.shape)
    print("Number of removed rows:", orginal_shape[0] - df.shape[0])
    print("\n")
    return df


def one_hot_encode_sequences(df, padding_length):
    df = filter_non_aa(df)
    tokenizer = Tokenizer(char_level=True)
    tokenizer.fit_on_texts(df['Sequence'])
    sequences_numeric = tokenizer.texts_to_sequences(df['Sequence'])
    sequences_padded = pad_sequences(sequences_numeric, maxlen=padding_length, padding='post', truncating='post')
    one_hot_sequences = np.zeros((len(sequences_padded), padding_length, (len(tokenizer.word_index) + 1)))
    for i, sequence in enumerate(sequences_padded):
        for j, char_index in enumerate(sequence):
            if char_index != 0:  # Skip padding
                one_hot_sequences[i, j, char_index] = 1
    one_hot_sequences = one_hot_sequences[:,:,1:]
    return one_hot_sequences, df['has_hmm'], pd.DataFrame(df['length'])

In [17]:
folders = ['Nitrosomonas_europaea', 'Nitrosomonas_ureae', 'Nitrosospira_briensis', 'Candidatus_Methylopumilus_turicensis', 'Aquincola_tertiaricarbonis']  # Adjust as necessary

# Dictionaries to store processed data
processed_data = {
    'short': {},
    'medium': {},
    'long': {},
    'meta': {}
}

for folder in folders:
    lorfs_short_path = f'Data/Test/{folder}/lorfs_short.csv'
    lorfs_medium_path = f'Data/Test/{folder}/lorfs_medium.csv'
    lorfs_long_path = f'Data/Test/{folder}/lorfs_long.csv'
    
    lorfs_short = pd.read_csv(lorfs_short_path).sort_values(by='length')
    lorfs_medium = pd.read_csv(lorfs_medium_path).sort_values(by='length')
    lorfs_long = pd.read_csv(lorfs_long_path).sort_values(by='length')
    
    processed_short = one_hot_encode_sequences(lorfs_short, 100)
    processed_medium = one_hot_encode_sequences(lorfs_medium, 400)
    processed_long = one_hot_encode_sequences(lorfs_long, 1000)
    
    processed_data['short'][folder] = processed_short
    processed_data['medium'][folder] = processed_medium
    processed_data['long'][folder] = processed_long
    processed_data['meta'][folder] = pd.read_csv(f'Data/Test/{folder}/genome_info.csv')
    



# Now `processed_data` contains all the processed data indexed by length category and folder name

Original shape: (25635, 5)
New shape after filtering: (25634, 5)
Number of removed rows: 1


Original shape: (4680, 5)
New shape after filtering: (4680, 5)
Number of removed rows: 0


Original shape: (711, 5)
New shape after filtering: (711, 5)
Number of removed rows: 0


Original shape: (27960, 5)
New shape after filtering: (27959, 5)
Number of removed rows: 1


Original shape: (3405, 5)
New shape after filtering: (3405, 5)
Number of removed rows: 0


Original shape: (762, 5)
New shape after filtering: (762, 5)
Number of removed rows: 0


Original shape: (29928, 5)
New shape after filtering: (29928, 5)
Number of removed rows: 0


Original shape: (5750, 5)
New shape after filtering: (5750, 5)
Number of removed rows: 0


Original shape: (779, 5)
New shape after filtering: (779, 5)
Number of removed rows: 0


Original shape: (13879, 5)
New shape after filtering: (13878, 5)
Number of removed rows: 1


Original shape: (1605, 5)
New shape after filtering: (1605, 5)
Number of removed rows: 0

## Models

In [18]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


# Function to predict and evaluate using the processed_data dictionary
def predict_and_evaluate_with_processed_data(models, processed_data, flat = 1):
    evaluation_results = {}
    
    for size in ['short', 'medium', 'long']:
        size_results = {}
        for folder in processed_data[size]:
            data, targets, _ = processed_data[size][folder]  # Assuming this structure
            if flat:
                data_flat = data.reshape(data.shape[0], -1)
            else:
                data_flat = data
            
            predictions = models[size].predict(data_flat)
            binary_predictions = [1 if i > 0.5 else 0 for i in predictions.ravel()]
            
            accuracy = accuracy_score(targets, binary_predictions)
            confusion_mat = confusion_matrix(targets, binary_predictions)
            
            size_results[folder] = {'accuracy': accuracy, 'confusion_matrix': confusion_mat, 'metadata': processed_data['meta'][folder]}
        
        evaluation_results[size] = size_results

    return evaluation_results

def print_summary(all_accuracies):
    for size, results in all_accuracies.items():
        print(f"--- {size.upper()} DATASET RESULTS ---")
        for folder, metrics in results.items():
            # print superkingdom, phylum, class, order, family, genus, species from meta
            meta = metrics['metadata']
            print(f"Folder: {folder}")
            print(f"Tax: {meta['superkingdom'].values[0]}, {meta['phylum'].values[0]}, {meta['class'].values[0]}, {meta['order'].values[0]}, {meta['family'].values[0]}, {meta['genus'].values[0]}, {meta['species'].values[0]}")
            print(f"Accuracy: {metrics['accuracy']:.4f}")
            print("Confusion Matrix:")
            print(metrics['confusion_matrix'])
            print("\n")
        print("\n")

In [19]:
# Initialize a dictionary to hold the loaded models
base_dir = 'Models/Dense'
dataset_sizes = ['short', 'medium', 'long']
models = {}

# Loop through the dataset sizes, load each model, and add it to the dictionary
for size in dataset_sizes:
    model_name = f'{size}_dataset_model.keras'
    model_path = os.path.join(base_dir, model_name)
    models[size] = load_model(model_path)
# Call the evaluation function with the loaded models and the processed_data dictionary
all_accuracies = predict_and_evaluate_with_processed_data(models, processed_data)

print_summary(all_accuracies)

145/145 [==============================] - 0s 805us/step
--- SHORT DATASET RESULTS ---
Folder: Nitrosomonas_europaea
Tax: Bacteria, Pseudomonadota, Betaproteobacteria, Nitrosomonadales, Nitrosomonadaceae, Nitrosomonas, Nitrosomonas europaea
Accuracy: 0.5765
Confusion Matrix:
[[13371 10165]
 [  692  1406]]


Folder: Nitrosomonas_ureae
Tax: Bacteria, Pseudomonadota, Betaproteobacteria, Nitrosomonadales, Nitrosomonadaceae, Nitrosomonas, Nitrosomonas ureae
Accuracy: 0.6067
Confusion Matrix:
[[15573  9944]
 [ 1052  1390]]


Folder: Nitrosospira_briensis
Tax: Bacteria, Pseudomonadota, Betaproteobacteria, Nitrosomonadales, Nitrosomonadaceae, Nitrosospira, Nitrosospira briensis
Accuracy: 0.5658
Confusion Matrix:
[[15467 12178]
 [  818  1465]]


Folder: Candidatus_Methylopumilus_turicensis
Tax: Bacteria, Pseudomonadota, Betaproteobacteria, Nitrosomonadales, Methylophilaceae, Candidatus Methylopumilus, Candidatus Methylopumilus turicensis
Accuracy: 0.6204
Confusion Matrix:
[[7946 4719]
 [ 549  6

### RNN

In [20]:
# Initialize a dictionary to hold the loaded models
base_dir = 'Models/RNN'
dataset_sizes = ['short', 'medium', 'long']
models = {}

# Loop through the dataset sizes, load each model, and add it to the dictionary
for size in dataset_sizes:
    model_name = f'{size}_dataset_model.keras'
    model_path = os.path.join(base_dir, model_name)
    models[size] = load_model(model_path)
# Call the evaluation function with the loaded models and the processed_data dictionary
all_accuracies = predict_and_evaluate_with_processed_data(models, processed_data, flat = 0)

print_summary(all_accuracies)

145/145 [==============================] - 3s 19ms/step
--- SHORT DATASET RESULTS ---
Folder: Nitrosomonas_europaea
Tax: Bacteria, Pseudomonadota, Betaproteobacteria, Nitrosomonadales, Nitrosomonadaceae, Nitrosomonas, Nitrosomonas europaea
Accuracy: 0.6209
Confusion Matrix:
[[14632  8904]
 [  813  1285]]


Folder: Nitrosomonas_ureae
Tax: Bacteria, Pseudomonadota, Betaproteobacteria, Nitrosomonadales, Nitrosomonadaceae, Nitrosomonas, Nitrosomonas ureae
Accuracy: 0.6507
Confusion Matrix:
[[16994  8523]
 [ 1244  1198]]


Folder: Nitrosospira_briensis
Tax: Bacteria, Pseudomonadota, Betaproteobacteria, Nitrosomonadales, Nitrosomonadaceae, Nitrosospira, Nitrosospira briensis
Accuracy: 0.6389
Confusion Matrix:
[[17822  9823]
 [  985  1298]]


Folder: Candidatus_Methylopumilus_turicensis
Tax: Bacteria, Pseudomonadota, Betaproteobacteria, Nitrosomonadales, Methylophilaceae, Candidatus Methylopumilus, Candidatus Methylopumilus turicensis
Accuracy: 0.6698
Confusion Matrix:
[[8695 3970]
 [ 612  60